SELECT "listing_events"."id" AS "id",
  "listing_events"."created_at" AS "created_at",
  "listing_events"."updated_at" AS "updated_at",
  "listing_events"."deleted_at" AS "deleted_at",
  "listing_events"."listing_block_height" AS "listing_block_height",
  "listing_events"."block_time" AS "block_time",
  CAST("listing_events"."seller" AS TEXT) AS "seller",
  CAST("listing_events"."player" AS TEXT) AS "player",
  CAST("listing_events"."play_type" AS TEXT) AS "play_type",
  CAST("listing_events"."set_id" AS TEXT) AS "set_id",
  CAST("listing_events"."play_id" AS TEXT) AS "play_id",
  "listing_events"."serial_number" AS "serial_number",
  "listing_events"."moment_id" AS "moment_id",
  "listing_events"."price" AS "price",
  CAST("set_play_metadata"."set_play_flow_id" AS TEXT) AS "set_play_flow_id",
  CAST("set_play_metadata"."set_play_guid" AS TEXT) AS "set_play_guid",
  "set_play_metadata"."created_at" AS "created_at (set_play_metadata)",
  "set_play_metadata"."updated_at" AS "updated_at (set_play_metadata)",
  "set_play_metadata"."deleted_at" AS "deleted_at (set_play_metadata)",
  "set_play_metadata"."set_id" AS "set_id (set_play_metadata)",
  "set_play_metadata"."play_id" AS "play_id (set_play_metadata)",
  CAST("set_play_metadata"."set_guid" AS TEXT) AS "set_guid",
  CAST("set_play_metadata"."play_guid" AS TEXT) AS "play_guid",
  CAST("set_play_metadata"."play_category" AS TEXT) AS "play_category",
  "set_play_metadata"."play_circulation_count" AS "play_circulation_count",
  "set_play_metadata"."play_retired" AS "play_retired",
  CAST("set_play_metadata"."play_type" AS TEXT) AS "play_type (set_play_metadata)",
  CAST("set_play_metadata"."play_version" AS TEXT) AS "play_version",
  "set_play_metadata"."set_locked" AS "set_locked",
  "set_play_metadata"."set_series_number" AS "set_series_number",
  CAST("set_play_metadata"."set_series_name" AS TEXT) AS "set_series_name",
  CAST("set_play_metadata"."set_version" AS TEXT) AS "set_version",
  CAST("set_play_metadata"."set_visual_id" AS TEXT) AS "set_visual_id",
  CAST("set_play_metadata"."birth_date" AS TEXT) AS "birth_date",
  CAST("set_play_metadata"."current_team" AS TEXT) AS "current_team",
  "set_play_metadata"."date_of_moment" AS "date_of_moment",
  "set_play_metadata"."draft_year" AS "draft_year",
  CAST("set_play_metadata"."jersey_number" AS TEXT) AS "jersey_number",
  "set_play_metadata"."player_id" AS "player_id",
  CAST("set_play_metadata"."player_name" AS TEXT) AS "player_name",
  CAST("set_play_metadata"."primary_position" AS TEXT) AS "primary_position",
  CAST("set_play_metadata"."team_at_moment" AS TEXT) AS "team_at_moment",
  "set_play_metadata"."away_team_score" AS "away_team_score",
  "set_play_metadata"."home_team_score" AS "home_team_score",
  CAST("set_play_metadata"."away_team_name" AS TEXT) AS "away_team_name",
  CAST("set_play_metadata"."home_team_name" AS TEXT) AS "home_team_name",
  CAST("set_play_metadata"."nba_season" AS TEXT) AS "nba_season"
FROM "public"."listing_events" "listing_events"
  INNER JOIN "public"."set_play_metadata" "set_play_metadata" ON ((CAST("listing_events"."play_id" AS TEXT) = CAST("set_play_metadata"."play_guid" AS TEXT)) AND (CAST("listing_events"."set_id" AS TEXT) = CAST("set_play_metadata"."set_guid" AS TEXT)))